### PR TITLE
Do not restart service in case of crash or auxiliary process direct exit

### LINKED ISSUE #138: WebProcess restarts when page is closed
Removing wpeview from view hierarchy causes web process to restart because Android system considers it as a crash

```
2022-10-17 23:39:38.769  1999-3033  ActivityManager         system_process                       I  Process com.wpe.tools.minibrowser:WPEWebProcess0 (pid 28393) has died: fore BTOP
2022-10-17 23:39:38.654 28345-28376 chatty                  com.wpe.tools.minibrowser            I  uid=10176(com.wpe.tools.minibrowser) RenderThread identical 4 lines
2022-10-17 23:39:38.657 28345-28376 EGL_emulation           com.wpe.tools.minibrowser            D  eglMakeCurrent: 0xdcda3c00: ver 3 1 (tinfo 0xd1841260)
2022-10-17 23:39:38.771  1747-1747  Zygote                  pid-1747                             I  Process 28393 exited cleanly (0)
2022-10-17 23:39:38.771  1999-2046  libprocessgroup         system_process                       I  Successfully killed process cgroup uid 10176 pid 28393 in 0ms
2022-10-17 23:39:38.773  1999-3033  ActivityManager         system_process                       W  Scheduling restart of crashed service com.wpe.tools.minibrowser/com.wpe.wpe.services.WPEServices$WebProcessService0 in 1000ms
2022-10-17 23:39:38.800 28345-28345 WPEServiceConnection    com.wpe.tools.minibrowser            I  onServiceDisconnected() name: ComponentInfo{com.wpe.tools.minibrowser/com.wpe.wpe.services.WPEServices$WebProcessService0}
2022-10-17 23:39:38.920 28345-28376 EGL_emulation           com.wpe.tools.minibrowser            D  eglMakeCurrent: 0xdcda3c00: ver 3 1 (tinfo 0xd1841260)
2022-10-17 23:39:39.798  1747-1747  Zygote                  pid-1747                             D  Forked child process 28581
2022-10-17 23:39:39.803  1999-2045  ActivityManager         system_process                       I  Start proc 28581:com.wpe.tools.minibrowser:WPEWebProcess0/u0a176 for service {com.wpe.tools.minibrowser/com.wpe.wpe.services.WPEServices$WebProcessService0}
2022-10-17 23:39:39.808 28581-28581 :WPEWebProcess          pid-28581                            I  Late-enabling -Xcheck:jni
2022-10-17 23:39:39.843 28581-28581 :WPEWebProcess          pid-28581                            E  Unknown bits set in runtime_flags: 0x8000
2022-10-17 23:39:39.844 28581-28581 :WPEWebProcess          pid-28581                            W  Unexpected CPU variant for X86 using defaults: x86
---------------------------- PROCESS STARTED (28581) for package com.wpe.tools.minibrowser ----------------------------
2022-10-17 23:39:40.049 28345-28376 EGL_emulation           com.wpe.tools.minibrowser            D  eglMakeCurrent: 0xdcda3c00: ver 3 1 (tinfo 0xd1841260)
2022-10-17 23:39:40.082 28581-28581 WPEService              com.wpe.tools.minibrowser            I  onCreate()
2022-10-17 23:39:40.167 28581-28581 :WPEWebProcess          com.wpe.tools.minibrowser            W  CheckJNI: method to register "initializeMain" not in the given class. This is slow, consider changing your RegisterNatives calls.
2022-10-17 23:39:40.167 28581-28581 :WPEWebProcess          com.wpe.tools.minibrowser            W  CheckJNI: method to register "setupEnvironment" not in the given class. This is slow, consider changing your RegisterNatives calls.
2022-10-17 23:39:40.173 28581-28581 WPE Glue                com.wpe.tools.minibrowser            V  Glue::setupEnvironment()
2022-10-17 23:39:40.211 28581-28581 GStreamer               com.wpe.tools.minibrowser            I  GStreamer initialization complete
2022-10-17 23:39:40.212 28581-28581 WPEService              com.wpe.tools.minibrowser            I  onBind()
2022-10-17 23:39:40.217 28345-28345 WPEServiceConnection    com.wpe.tools.minibrowser            W  onServiceConnected() name: ComponentInfo{com.wpe.tools.minibrowser/com.wpe.wpe.services.WPEServices$WebProcessService0} called more than once
2022-10-17 23:39:41.479  1753-1933  audio_hw_generic        pid-1753                             W  Not supplying enough data to HAL, expected position 15523515 , only wrote 15386758
2022-10-17 23:39:42.570 28345-28345 PressureMonitor         com.wpe.tools.minibrowser            W  type=1400 audit(0.0:8524): avc: denied { read } for name="zoneinfo" dev="proc" ino=4026531860 scontext=u:r:untrusted_app:s0:c176,c256,c512,c768 tcontext=u:object_r:proc_zoneinfo:s0 tclass=file permissive=0 app=com.wpe.tools.minibrowser
2022-10-17 23:39:43.038  1999-2043  memtrack                system_process                       E  Couldn't load memtrack module
2022-10-17 23:39:43.038  1999-2043  android.os.Debug        system_process                       W  failed to get memory consumption info: -1
2022-10-17 23:39:43.049  1999-2043  memtrack                system_process                       E  Couldn't load memtrack module
2022-10-17 23:39:43.049  1999-2043  android.os.Debug        system_process                       W  failed to get memory consumption info: -1
2022-10-17 23:39:47.570 28345-28345 PressureMonitor         com.wpe.tools.minibrowser            W  type=1400 audit(0.0:8525): avc: denied { read } for name="zoneinfo" dev="proc" ino=4026531860 scontext=u:r:untrusted_app:s0:c176,c256,c512,c768 tcontext=u:object_r:proc_zoneinfo:s0 tclass=file permissive=0 app=com.wpe.tools.minibrowser
2022-10-17 23:39:50.013  1999-2043  UsageStatsService       system_process                       I  User[0] Flushing usage stats to disk
```

### PR DESCRIPTION
**Pull request by zhani**
In some cases WebProcess and NetworkProcess call exit(0) directly and in such cases Android tries to restart bound service. This is wrong because it's not Android system that should restart auxiliary processes but WebKit.

Fixes #138 138

### CODE REVIEW

File: wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java [hunk 1]
```diff
@@ -43,12 +43,17 @@ public final class WPEServiceConnection implements ServiceConnection {
     private final ProcessType processType;
     private ParcelFileDescriptor parcelFd;
 
-    public WPEServiceConnection(long pid, @NonNull ProcessType processType, @NonNull ParcelFileDescriptor parcelFd) {
+    private WPEServiceConnectionDelegate delegate;
```
Comment (neodesys) [inline wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java:46]: Should be `final` according to the usage you are doing of the reference later on.

**Review by neodesys — CHANGES_REQUESTED** [review]
:+1: I just added very few comments to improvement code resilience, but nothing important :wink:

File: wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java [hunk 2]
```diff
@@ -43,12 +43,17 @@ public final class WPEServiceConnection implements ServiceConnection {
...
+
+    public WPEServiceConnection(long pid, @NonNull ProcessType processType, @NonNull ParcelFileDescriptor parcelFd,
+                                WPEServiceConnectionDelegate delegate) {
```
[the remark this answers is not in the document]
Comment (zhani) [reply wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java]: fixed accordingly

File: wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java (hunk 1 above)
Comment (zhani) [reply wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java]: fixed accordingly

**Review by neodesys — APPROVED** [review]
